name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE-GROUP: rg-eshoponweb-lab
  LOCATION: eastus
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: a6f9a103-b417-4c55-a2bf-b30bf0c929e7
  WEBAPP-NAME: eshoponweb-webapp-lab

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/Web/Web.csproj -c Release -o ./publish-output

      - name: Zip the app
        # This zips the content inside the publish-output folder into app.zip
        run: zip -r ../app.zip .
        working-directory: ./publish-output

      - name: Upload Web App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net-app-artifact
          path: app.zip
          
      - name: Upload Bicep Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template-artifact
          path: ${{ env.TEMPLATE-FILE }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download Web App
        uses: actions/download-artifact@v4
        with:
          name: net-app-artifact
          path: ./artifacts

      - name: Download Bicep Template
        uses: actions/download-artifact@v4
        with:
          name: bicep-template-artifact
          path: ./infra

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          # The artifact download puts the file directly in the path specified
          template: ./infra/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false   
    
      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy --name ${{ env.WEBAPP-NAME }} \
                             --resource-group ${{ env.RESOURCE-GROUP }} \
                             --src-path ./artifacts/app.zip \
                             --type zip
